In [2]:
pip install pandas sqlalchemy psycopg2-binary

Requirement already satisfied: pandas in .\.venv-1\Lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in .\.venv-1\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg2-binary in .\.venv-1\Lib\site-packages (2.9.12)
Requirement already satisfied: numpy>=1.26.0 in .\.venv-1\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv-1\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv-1\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: greenlet>=1 in .\.venv-1\Lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in .\.venv-1\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in .\.venv-1\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [3]:
country_series= pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\Country-Series - Metadata.csv', encoding='latin-1')
all_countries_data=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_ALLCountries_Data.csv', encoding='latin-1')
country_metadata=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_CountryMetaData.csv', encoding='latin-1')
country_metadata['Latest population census'] = pd.to_numeric(
    country_metadata['Latest population census'], errors='coerce'
)
country_metadata.loc[106, 'Latest population census'] = 1987
country_metadata['Region'] = country_metadata['Region'].fillna(country_metadata['Long Name'])
income_group_mode = country_metadata['Income Group'].mode(dropna=True)
if not income_group_mode.empty:
    country_metadata['Income Group'] = country_metadata['Income Group'].fillna(income_group_mode.iloc[0])
currency_unit_mode = country_metadata['Currency Unit'].mode(dropna=True)
if not currency_unit_mode.empty:
    country_metadata['Currency Unit'] = country_metadata['Currency Unit'].fillna(currency_unit_mode.iloc[0])
country_metadata = country_metadata.fillna('NA')
foot_note=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_FootNoteMetaData.csv', encoding='latin-1')
series_metadata=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_SeriesMetaData.csv', encoding='latin-1')
series_metadata = series_metadata.drop(
    columns=[
        col for col in [
            'License Type',
            'Limitations and exceptions',
            'General comments'
        ]
        if col in series_metadata.columns
    ],
    errors='ignore'
)
for column in ['Short definition', 'Dataset']:
    if column in series_metadata.columns:
        mode = series_metadata[column].mode(dropna=True)
        if not mode.empty:
            series_metadata[column] = series_metadata[column].fillna(mode.iloc[0])
country_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 30 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               134 non-null    str
 1   Long Name                                          134 non-null    str
 2   Income Group                                       134 non-null    str
 3   Region                                             134 non-null    str
 4   Lending category                                   134 non-null    str
 5   Other groups                                       134 non-null    str
 6   Currency Unit                                      134 non-null    str
 7   Latest population census                           134 non-null    object
 8   Latest household survey                            134 non-null    str
 9   Special Notes                                      134 non-null    str
 10  National accounts base year                        134 non-null    str
 11  National accounts reference year                   134 non-null    object
 12  System of National Accounts                        134 non-null    str
 13  SNA price valuation                                134 non-null    str
 14  PPP survey years                                   134 non-null    str
 15  Balance of Payments Manual in use                  134 non-null    str
 16  External debt Reporting status                     134 non-null    str
 17  System of trade                                    134 non-null    str
 18  Government Accounting concept                      134 non-null    str
 19  IMF data dissemination standard                    134 non-null    str
 20  Source of most recent Income and expenditure data  134 non-null    str
 21  Vital registration complete                        134 non-null    str
 22  Latest agricultural census                         134 non-null    str
 23  Latest industrial data                             134 non-null    object
 24  Latest trade data                                  134 non-null    object
 25  Latest water withdrawal data                       134 non-null    object
 26  2-alpha code                                       134 non-null    str
 27  WB-2 code                                          134 non-null    str
 28  Table Name                                         134 non-null    str
 29  Short Name                                         134 non-null    str
dtypes: object(5), str(25)
memory usage: 114.5+ KB

In [4]:
country_series= pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\Country-Series - Metadata.csv', encoding='latin-1')
all_countries_data=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_ALLCountries_Data.csv', encoding='latin-1')
country_metadata=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_CountryMetaData.csv', encoding='latin-1')
country_metadata['Latest population census'] = pd.to_numeric(
    country_metadata['Latest population census'], errors='coerce'
)
country_metadata.loc[106, 'Latest population census'] = 1987
country_metadata['Region'] = country_metadata['Region'].fillna(country_metadata['Long Name'])
income_group_mode = country_metadata['Income Group'].mode(dropna=True)
if not income_group_mode.empty:
    country_metadata['Income Group'] = country_metadata['Income Group'].fillna(income_group_mode.iloc[0])
currency_unit_mode = country_metadata['Currency Unit'].mode(dropna=True)
if not currency_unit_mode.empty:
    country_metadata['Currency Unit'] = country_metadata['Currency Unit'].fillna(currency_unit_mode.iloc[0])
country_metadata = country_metadata.fillna('NA')
foot_note=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_FootNoteMetaData.csv', encoding='latin-1')
series_metadata=pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_SeriesMetaData.csv', encoding='latin-1')
series_metadata = series_metadata.drop(
    columns=[
        col for col in [
            'License Type',
            'Limitations and exceptions',
            'General comments'
        ]
        if col in series_metadata.columns
    ],
    errors='ignore'
)
for column in ['Short definition', 'Dataset']:
    if column in series_metadata.columns:
        mode = series_metadata[column].mode(dropna=True)
        if not mode.empty:
            series_metadata[column] = series_metadata[column].fillna(mode.iloc[0])

In [5]:
source_df = pd.read_csv(r'C:\Users\rajanaga22\mini_pro_two\IDS_ALLCountries_Data.csv', encoding='latin-1')
year_columns = [col for col in source_df.columns if str(col).isdigit()]
id_columns = [
    'Country Name',
    'Country Code',
    'Series Code'
]

source_df['Country Name'] = source_df['Country Name'].astype('string').str.strip()
source_df = source_df.loc[
    source_df['Country Name'].notna()
    & source_df['Country Name'].ne('')
    & source_df['Country Name'].ne('Unknown')
].copy()

all_countries_data = (
    source_df.loc[:, id_columns + year_columns]
    .melt(
        id_vars=id_columns,
        value_vars=year_columns,
        var_name='Year',
        value_name='Value'
    )
)

all_countries_data['Year'] = pd.to_numeric(all_countries_data['Year'], errors='coerce')
all_countries_data['Value'] = pd.to_numeric(all_countries_data['Value'], errors='coerce').fillna(0)
all_countries_data = (
    all_countries_data.groupby(
        ['Country Name', 'Country Code', 'Series Code', 'Year'],
        as_index=False
    )['Value']
    .sum()
    .sort_values(['Country Name', 'Series Code', 'Year'])
    .reset_index(drop=True)
)

all_countries_data.head()

  Country Name Country Code     Series Code  Year  Value
0  Afghanistan   AFG         BM.GSR.TOTL.CD  2000    0.0
1  Afghanistan   AFG         BM.GSR.TOTL.CD  2001    0.0
2  Afghanistan   AFG         BM.GSR.TOTL.CD  2002    0.0
3  Afghanistan   AFG         BM.GSR.TOTL.CD  2003    0.0
4  Afghanistan   AFG         BM.GSR.TOTL.CD  2004    0.0

In [6]:
year_wise_totals = (
    all_countries_data.groupby(['Country Name', 'Year'], as_index=False)['Value']
    .sum()
    .sort_values(['Country Name', 'Year'])
    .reset_index(drop=True)
)

year_wise_totals.head()

  Country Name  Year  Value
0  Afghanistan  2000    0.0
1  Afghanistan  2001    0.0
2  Afghanistan  2002    0.0
3  Afghanistan  2003    0.0
4  Afghanistan  2004    0.0

In [7]:
foot_note.info()

<class 'pandas.DataFrame'>
RangeIndex: 2673 entries, 0 to 2672
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          2673 non-null   str
 1   Country Code  2673 non-null   str
 2   Series Code   2673 non-null   str
 3   Time Code     2673 non-null   str
 4   Description   2673 non-null   str
dtypes: str(5)
memory usage: 642.6 KB

In [8]:
series_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 574 entries, 0 to 573
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Code                574 non-null    str
 1   Indicator Name      574 non-null    str
 2   Short definition    574 non-null    str
 3   Long definition     574 non-null    str
 4   Source              574 non-null    str
 5   Topic               574 non-null    str
 6   Dataset             574 non-null    str
 7   Periodicity         574 non-null    str
 8   Aggregation method  574 non-null    str
dtypes: str(9)
memory usage: 729.0 KB

In [9]:
country_series.info()

<class 'pandas.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Type          375 non-null    str
 1   Country Code  375 non-null    str
 2   Series Code   375 non-null    str
 3   Description   375 non-null    str
dtypes: str(4)
memory usage: 112.0 KB

In [10]:
all_countries_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1574450 entries, 0 to 1574449
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Country Name  1574450 non-null  string
 1   Country Code  1574450 non-null  str
 2   Series Code   1574450 non-null  str
 3   Year          1574450 non-null  int64
 4   Value         1574450 non-null  float64
dtypes: float64(1), int64(1), str(2), string(1)
memory usage: 117.6 MB

In [11]:
all_countries_data

        Country Name Country Code     Series Code  Year       Value
0        Afghanistan   AFG         BM.GSR.TOTL.CD  2000         0.0
1        Afghanistan   AFG         BM.GSR.TOTL.CD  2001         0.0
2        Afghanistan   AFG         BM.GSR.TOTL.CD  2002         0.0
3        Afghanistan   AFG         BM.GSR.TOTL.CD  2003         0.0
4        Afghanistan   AFG         BM.GSR.TOTL.CD  2004         0.0
...              ...          ...             ...   ...         ...
1574445     Zimbabwe   ZWE            SP.POP.TOTL  2020  15526888.0
1574446     Zimbabwe   ZWE            SP.POP.TOTL  2021  15797210.0
1574447     Zimbabwe   ZWE            SP.POP.TOTL  2022  16069056.0
1574448     Zimbabwe   ZWE            SP.POP.TOTL  2023  16340822.0
1574449     Zimbabwe   ZWE            SP.POP.TOTL  2024  16634373.0

[1574450 rows x 5 columns]

In [12]:
country_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 30 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Code                                               134 non-null    str
 1   Long Name                                          134 non-null    str
 2   Income Group                                       134 non-null    str
 3   Region                                             134 non-null    str
 4   Lending category                                   134 non-null    str
 5   Other groups                                       134 non-null    str
 6   Currency Unit                                      134 non-null    str
 7   Latest population census                           134 non-null    object
 8   Latest household survey                            134 non-null    str
 9   Special Notes                                      134 non-null    str
 10  National accounts base year                        134 non-null    str
 11  National accounts reference year                   134 non-null    object
 12  System of National Accounts                        134 non-null    str
 13  SNA price valuation                                134 non-null    str
 14  PPP survey years                                   134 non-null    str
 15  Balance of Payments Manual in use                  134 non-null    str
 16  External debt Reporting status                     134 non-null    str
 17  System of trade                                    134 non-null    str
 18  Government Accounting concept                      134 non-null    str
 19  IMF data dissemination standard                    134 non-null    str
 20  Source of most recent Income and expenditure data  134 non-null    str
 21  Vital registration complete                        134 non-null    str
 22  Latest agricultural census                         134 non-null    str
 23  Latest industrial data                             134 non-null    object
 24  Latest trade data                                  134 non-null    object
 25  Latest water withdrawal data                       134 non-null    object
 26  2-alpha code                                       134 non-null    str
 27  WB-2 code                                          134 non-null    str
 28  Table Name                                         134 non-null    str
 29  Short Name                                         134 non-null    str
dtypes: object(5), str(25)
memory usage: 114.5+ KB

In [13]:
all_countries_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1574450 entries, 0 to 1574449
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   Country Name  1574450 non-null  string
 1   Country Code  1574450 non-null  str
 2   Series Code   1574450 non-null  str
 3   Year          1574450 non-null  int64
 4   Value         1574450 non-null  float64
dtypes: float64(1), int64(1), str(2), string(1)
memory usage: 117.6 MB